//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSolDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class opeEmpleado
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public int FkIdArea { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public decimal Sueldo { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public System.DateTime Fecha_Modificacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual catArea catArea { get; set; }
    }
}
