//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSolDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class opeLog
    {
        public int Id { get; set; }
        public string NombreClase { get; set; }
        public string NombreMetodo { get; set; }
        public int LineaCodigo { get; set; }
        public string MesajeError { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
    }
}
